# Generated by Django 4.1.6 on 2023-02-21 22:40

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pages.models.get_about_dir)),
                ('text', models.TextField(max_length=2000)),
            ],
        ),
    ]
