# Generated by Django 4.1.6 on 2023-02-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_about_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slogen', models.TextField(max_length=1000)),
            ],
        ),
    ]
